apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oldsix-tls
  namespace: cert-manager
spec:
  ipAddresses:
  - 192.168.222.14
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: my-ca-issuer
  secretName: oldsix-tls
  duration: 87600h #10年
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
