apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ks-webhook
  namespace: kube-system
spec:
  secretName: ks-webhook-certs
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - ks-webhook-controller-svc
  - ks-webhook-controller-svc.kube-system.svc
  - ks-webhook-controller-svc.kube-system.svc.cluster.local
  duration: 87600h 
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
