apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-ks-cfg
  labels:
    app: admission-webhook-ks
webhooks:
  - name: mutating-addvpclabel.ks.com
    clientConfig:
      service:
        name: ks-webhook-controller-svc
        namespace: kube-system
        path: /mutate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXakNDQWtLZ0F3SUJBZ0lRS3hQa1dncWdtODNkcXQ2cndXZFR6VEFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSXpNRFV6TURBNE1Ea3hNMW9YRFRNek1EVXlOekE0TURreE0xb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUFrWC9DanhWQlQ4WTVDcW8xYUV2UFU3cXUxeEtXZVhWV2p2Rng1CjAvdElnREppYXJ2RVFaQnpVaHoydnY5bkhXT05XdXdaa0FqN2hYZXVaL0FIWTI5M1B6ZjdRbzE2UWdveUVIWXcKeGJ4U2tRRnhuNGx2WUpZQXc2UWVlbHV3OUpwMHRpekJTLzY3SXBRc0dLN2hlMHE1K2prR0N6bGxiYjBRWHdEcgpTVkZhSUtUY3Q0L1hNSlFCMkNmanJSVEZ5NXpFb3FWZGRaNmRPanZNeSsyQnRyWVhQR0ZQOEVaYkdGS1N6UDVoCjhTbDVySGErdEVXLzd3NWpQZmVOM0piRE1MVUJGQ2FuUzAwL2JmVGZIVFB1amJOMmJhTlFNb2NWYi9xY3dYWXQKZ28vSUVGK3F2Ny9yRi9WTnNlV0NjeW1ndERxei80d01qYWJLVFcvWGpDc2FXdjhDQXdFQUFhT0J6ekNCekRBTwpCZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHCkExVWRFd0VCL3dRQ01BQXdnWXdHQTFVZEVRRUIvd1NCZ1RCL2dobHJjeTEzWldKb2IyOXJMV052Ym5SeWIyeHMKWlhJdGMzWmpnaWxyY3kxM1pXSm9iMjlyTFdOdmJuUnliMnhzWlhJdGMzWmpMbXQxWW1VdGMzbHpkR1Z0TG5OMgpZNEkzYTNNdGQyVmlhRzl2YXkxamIyNTBjbTlzYkdWeUxYTjJZeTVyZFdKbExYTjVjM1JsYlM1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFwS0lYLyt3cDI5K0Z0N2lvZUJFUUZvU3MKREcrcG9qUHV6eHFLUDFaZUlPakovWVhlckR0bWo4WUxaNHM0MVRmZTRSN0Q0a2xKMEJhQmd5c0x0MEUyLy9aRwpRUFBVbGN0MzgzRmd4RHhDb1NQQzlEcWpkekdaVjA5RGk5L3ZIdGNwMTFCRTFKcjFOSmFGcFdESWYyVC9zcmk1CmZPbVdUNFB0SzBMWmVDUjNnaFhPaEJjYmhrMVhTMkxTVnJIMDFEaklWRVhyZHptbFlPNER5VUlrazJtdHBJR1QKcVFwNVBCa0E3ZzA2NFVGOFRDQ0RsUktpREJGWElnWjZkM1ZsY2ZUQ3EwVlFQSGxhNzM2a1dSaVY5T0hJRFZQWApTdnNZa2pZbnZoM3ZQM3N1TURIZHRja21SRGFsL2h2Ulk2K21mNzlaWkc1ZnA1K2p1RkMyMFYwV2FMdlQrdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE","UPDATE" ]
        apiGroups: ["","apps"]
        apiVersions: ["v1"]
        resources: ["namespaces","deployments"]
      - operations: [ "CREATE","UPDATE","DELETE" ]
        apiGroups: ["tenant.kubesphere.io"]
        apiVersions: ["v1alpha1"]
        resources: ["workspaces"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
