apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name:  ks-webhook-controller-svc
  labels:
    app:  ks-webhook-controller
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app:  ks-webhook-controller
